    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    gov_id INTEGER DEFAULT nextval('gov_id'),    gov_id INTEGER DEFAULT nextval('gov_id'),
    name TEXT    name TEXT
););


CREATE TABLE gov_employee (CREATE TABLE gov_employee (

CREATE SEQUENCE gov_id START WITH 1000 INCREMENT BY 3;CREATE SEQUENCE gov_id START WITH 1000 INCREMENT BY 3;